### ISSUE TITLE
KeyError: 'DisplayText_Zho'

### ISSUE THREAD

**Issue by dongxiaoke** [ZHO-ZHO-ZHO/ComfyUI-Qwen-VL-API#1]

**Comment by dongxiaoke** [comment]
Error handling request
Traceback (most recent call last):
  File "D:\conda\envs\comfyui\lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "D:\conda\envs\comfyui\lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
  File "D:\conda\envs\comfyui\lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
  File "D:\ComfyUI\server.py", line 47, in cache_control
    response: web.Response = await handler(request)
  File "D:\ComfyUI\server.py", line 475, in post_prompt
    valid = execution.validate_prompt(prompt)
  File "D:\ComfyUI\execution.py", line 623, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
KeyError: 'DisplayText_Zho'
